### PR TITLE
Repo link update

### PR DESCRIPTION
**Pull request by AndriiMoskvin**

### CODE REVIEW

**Comment by balavor** [comment]
https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK - there is no such repository o_O

**Comment by AndriiMoskvin** [comment]
Yes, unfortunately.

**Comment by balavor** [comment]
Yeah, but... I mean, maybe the default value should be the releases repo?

**Comment by AndriiMoskvin** [comment]
Sure - @RomanTysiachnik RFR.

**Review by balavor — APPROVED** [review]

**Pull request merged**
