### PR TITLE
Add stencil and bash files

### PR DESCRIPTION
**Pull request by BohdanBilonoh**
Proposed to plug enum prism generation as submodule to use it through all SDK components

### CODE REVIEW

**Comment by AndriiMoskvin** [comment]
Where is this problem with dictionary?

**Comment by AndriiMoskvin** [comment]
@BogdanBilonog ?

**Comment by BohdanBilonoh** [comment]
@AndriiMoskvin after several hours the problem resolved itself

**Review by AndriiMoskvin — DISMISSED** [review]

**Comment by BohdanBilonoh** [comment]
https://github.com/krzysztofzablocki/Sourcery/issues/513

**Comment by AndriiMoskvin** [comment]
@BogdanBilonog Why it is still not merged?

**Comment by BohdanBilonoh** [comment]
@AndriiMoskvin  Waiting for are Sourcery release

**Comment by AndriiMoskvin** [comment]
@BogdanBilonog Still no release from Sourcery?

**Comment by BohdanBilonoh** [comment]
No :(

**Comment by AndriiMoskvin** [comment]
@BogdanBilonog is it still valid?

**Pull request closed without merging**
